# Generated by Django 6.0.1 on 2026-01-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "صبحانه"),
                            ("lunch", "ناهار"),
                            ("dinner", "شام"),
                        ],
                        max_length=20,
                        verbose_name="وعده غذایی",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="ظرفیت")),
                (
                    "reserved_count",
                    models.IntegerField(default=0, verbose_name="تعداد رزرو شده"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "منوی روزانه",
                "verbose_name_plural": "منوهای روزانه",
                "ordering": ["-date", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی غذا",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای غذا",
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام غذا")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "calories",
                    models.IntegerField(blank=True, null=True, verbose_name="کالری"),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="تصویر")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="وضعیت فعال بودن"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.foodcategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "غذا",
                "verbose_name_plural": "غذاها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(max_length=50, verbose_name="مقدار")),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.fooditem",
                        verbose_name="غذا",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.dailymenu",
                        verbose_name="منو",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم منو",
                "verbose_name_plural": "آیتم\u200cهای منو",
                "unique_together": {("menu", "food_item")},
            },
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="food_items",
            field=models.ManyToManyField(
                through="menu.MenuFoodItem",
                to="menu.fooditem",
                verbose_name="مواد غذایی",
            ),
        ),
    ]
