# Generated by Django 6.0.1 on 2026-02-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_transaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeRestaurantMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام غذا")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "صبحانه"),
                            ("lunch", "ناهار"),
                            ("dinner", "شام"),
                        ],
                        max_length=20,
                        verbose_name="وعده غذایی",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="در دسترس"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "منوی رستوران آزاد",
                "verbose_name_plural": "منوهای رستوران آزاد",
                "ordering": ["meal_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="FreeRestaurantReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_date", models.DateField(verbose_name="تاریخ رزرو")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "رزرو شده"),
                            ("cancelled", "لغو شده"),
                            ("consumed", "مصرف شده"),
                        ],
                        default="reserved",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.freerestaurantmenu",
                        verbose_name="غذا",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "رزرو رستوران آزاد",
                "verbose_name_plural": "رزروهای رستوران آزاد",
                "unique_together": {("user", "menu_item", "reservation_date")},
            },
        ),
    ]
