# Generated by Django 6.0.1 on 2026-02-01 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_deadline", models.TimeField(verbose_name="مهلت رزرو")),
                ("cancellation_deadline", models.TimeField(verbose_name="مهلت لغو")),
                (
                    "max_daily_reservations",
                    models.IntegerField(default=3, verbose_name="حداکثر رزرو روزانه"),
                ),
                (
                    "can_reserve_for_next_days",
                    models.IntegerField(
                        default=7, verbose_name="می توانید برای روزهای آینده رزرو کنید"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات رزرو",
                "verbose_name_plural": "تنظیمات رزرو",
            },
        ),
        migrations.CreateModel(
            name="FoodReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ رزرو"),
                ),
                ("meal_date", models.DateField(verbose_name="تاریخ غذا")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("confirmed", "تأیید شده"),
                            ("cancelled", "لغو شده"),
                            ("delivered", "تحویل داده شده"),
                            ("absent", "غایب"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reservation_qrcodes/",
                        verbose_name="کد qr",
                    ),
                ),
                (
                    "special_request",
                    models.TextField(
                        blank=True, null=True, verbose_name="درخواست ویژه"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.dailymenu",
                        verbose_name="منو",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دانشجو",
                    ),
                ),
            ],
            options={
                "verbose_name": "رزرو غذا",
                "verbose_name_plural": "رزرو غذا",
                "unique_together": {("student", "menu")},
            },
        ),
    ]
