# Generated by Django 6.0.1 on 2026-02-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="foodreservation",
            unique_together=set(),
        ),
    ]
